on:
  pull_request:
    types: [opened]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up docker compose
        uses: docker/compose-action@v2

      - name: Run infra
        run: |
          ./run-app-local.sh
      
      - name: Run tests
        run: |
          mkdir ./allure-results
          export CI=true
          ./run-test.sh