on:
  pull_request:
    types: [opened, synchronize]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2
        
      - name: Run infra
        run: |
          ./run-app-local.sh
      
      - name: Run tests
        run: |
          mkdir ./allure-results
          export CI=true
          ./run-tests.sh
          
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: ./allure-results
          
      - name: Checking
        run: |
          ls -a
          cd ./allure-results
          ls